# Generated by Django 5.0.2 on 2024-02-13 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
