# Generated by Django 5.0.2 on 2024-02-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_remove_post_cover_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
